version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
    docker:
      - image: cypress/base:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the Application
          command: npm run build

workflows:
  run-tests:
    jobs:
      - start-server
      - cypress/run:
          name: run-cypress-tests
          cypress-command: npx cypress run --component